# This is a TOML document.

test = 12_23_34.45_56_67e-2

binario = 0b11011011010
octal = 0o1234567
hexa = 0xFFFFF


title = "TOML \"QUOTE\" Example"
[1]
testing = [2001-01-20]

["owner"]
name = "Tom Preston-Werner"
dob = 0-05-27T07:32:00.999999+08:00z # First class dates
deb = 1979-05-27
dab = 07:32:00Z

[database]
server = "192.168.1.1"
ports = [ 8000, 8001, 8002 ]
connection_max = 5000
enabled = true
type = null
sl = '  string literal'

[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.\"alpha\"."delta"]
  ip = "10.0.0.1"
  dc = "eqdc10"
  inf = +infinity
  n = -nan

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]

inline = { test = "test", more = "more", name = null }

[[fruit]]
name = "potato"
flavour = 10